import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from dotenv import load_dotenv
from reports.pdf_report import generate_pdf

load_dotenv()

EMAIL_SENDER   = os.getenv("EMAIL_SENDER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_RECEIVER = os.getenv("EMAIL_RECEIVER")

def send_kpi_email(pdf_path="data/processed/kpi_report.pdf"):

    # Generate fresh PDF first
    generate_pdf(pdf_path)

    # ── Build Email ─────────────────────────────────────────
    msg = MIMEMultipart()
    msg["From"]    = EMAIL_SENDER
    msg["To"]      = EMAIL_RECEIVER
    msg["Subject"] = f"📊 KPI Report — {datetime.now().strftime('%B %d, %Y')}"

    body = f"""
<html><body style="font-family: Arial, sans-serif; color: #333; margin:0; padding:0;">
    <div style="max-width:600px; margin:auto; border:1px solid #ddd; border-radius:10px; overflow:hidden;">

        <!-- Header -->
        <div style="background:#1a1a2e; padding:30px; text-align:center;">
            <h1 style="color:white; margin:0; font-size:24px;">📊 KPI Summary Report</h1>
            <p style="color:#ccc; margin:8px 0 0; font-size:14px;">Generated {datetime.now().strftime('%B %d, %Y at %H:%M')}</p>
        </div>

        <!-- Body -->
        <div style="padding:30px;">
            <p style="font-size:15px;">Hello,</p>
            <p style="font-size:15px;">Please find attached your <strong>automated KPI Summary Report</strong> for 2024. The report includes a full breakdown of sales and revenue performance.</p>

            <!-- Highlights -->
            <h3 style="color:#00b4d8; border-bottom:2px solid #00b4d8; padding-bottom:6px;">📈 Report Highlights</h3>
            <ul style="font-size:14px; line-height:2;">
                <li>💰 Total Revenue, Profit & Profit Margin</li>
                <li>🧲 Customer Acquisition Cost (CAC)</li>
                <li>✅ Active vs Churned Customer Analysis</li>
                <li>📦 Revenue Breakdown by Product</li>
                <li>🌍 Regional Performance Comparison</li>
                <li>🏆 Top Salesperson Rankings</li>
                <li>📅 Monthly Revenue Trend (Jan–Dec 2024)</li>
            </ul>

            <!-- Note -->
            <div style="background:#f0f9ff; border-left:4px solid #00b4d8; padding:12px 16px; border-radius:4px; margin-top:20px;">
                <p style="margin:0; font-size:13px; color:#555;">📎 The full PDF report is attached to this email. Open it to view all tables and metrics in detail.</p>
            </div>

            <p style="font-size:14px; color:#888; margin-top:24px;">This report was automatically generated by your KPI Reporting System. No action is required.</p>
        </div>

        <!-- Footer -->
        <div style="background:#f5f5f5; padding:16px; text-align:center;">
            <p style="color:#aaa; font-size:12px; margin:0;">KPI Reporting System &nbsp;•&nbsp; {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
        </div>

    </div>
</body></html>
"""
    msg.attach(MIMEText(body, "html"))

    # ── Attach PDF ──────────────────────────────────────────
    with open(pdf_path, "rb") as f:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header("Content-Disposition",
                        f"attachment; filename=kpi_report_{datetime.now().strftime('%Y%m%d')}.pdf")
        msg.attach(part)

    # ── Send Email ──────────────────────────────────────────
    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(EMAIL_SENDER, EMAIL_PASSWORD)
            server.sendmail(EMAIL_SENDER, EMAIL_RECEIVER, msg.as_string())
        print(f"✅ Email sent successfully to {EMAIL_RECEIVER}")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

if __name__ == "__main__":
    send_kpi_email()